server:
  port: 8081

identity:
  jwt:
    issuer: "capstone"
    expiration: "PT1H"
  jwks:
    activeSignableKid: "key-20260514-133746"
    keyBaseLocation: "classpath:keys/"
    keys:
      - "key-20260514-133746"
      - "key-20260514-133748"
